### ISSUE TITLE
4-2 自动随机选择试题，更新自动选择试题逻辑

### ISSUE THREAD

**Issue by lanxichan** [12123ghh/testsystem#32]

**Comment by 12123ghhh** [comment]
教师设置试卷属性包括各种类型的题目的数量系统自动生成样卷，单选题、填空题、判断题每种题目数量不少于5题，简答题最少需要1题

**Comment by 12123ghhh** [comment]
试卷总分100分，单选题每道2分，判断，填空题每道1分，简答题根据剩余分数系统分配分数但不能低于5分
