### ISSUE TITLE
1 增加题目类型，选择、判断、填空、简答

### ISSUE THREAD

**Issue by lanxichan** [12123ghh/testsystem#33]

**Comment by 12123ghhh** [comment]
为questions新增question_type，stander_answer，right_error字段
question_type, 题目类型，包括单选，填空，判断，简答
stander_answer: 填空题，简答题的标准答案
right_error: 判断题答案

**Comment by 12123ghhh** [comment]
填空题，简答题的标准答案不能为空

**Comment by 12123ghhh** [comment]
单选题最少要两个选项
判断题答案只能为true或者flase

**Comment by 12123ghhh** [comment]
题目类型不能为空且只能是单选，填空，判断，简答其中一种
